// Based on https://stackoverflow.com/questions/1550249/programmatically-change-the-assemblyversion-and-assemblyfileversion-attributes
// and https://stackoverflow.com/questions/17123991/t4-reference-a-const-in-a-static-class-at-compile-time

// This is an autogenerated AssemblyInfo.cs file, it will be updated per build

using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

using ModioModNetworkerUpdater;
using MelonLoader;
[assembly: AssemblyTrademark(null)]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: MelonInfo(typeof(ModioModNetworkerUpdaterPlugin), ModioModNetworkerUpdaterPlugin.Name, "1.0.0", ModioModNetworkerUpdaterPlugin.Author, null)]

[assembly: MelonGame("Stress Level Zero", "BONELAB")]